# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/www',
                'doc_host': 'https://vguerra.github.io',
                'git_url': 'https://github.com/vguerra/www',
                'lib_path': 'www'},
  'syms': {'www.core': {'www.core.foo': ('core.html#foo', 'www/core.py')}}}
