project:
  type: website

format:
  html:
    theme: litera
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: none
  navbar:
    # background: primary
    search: true
    left:
      - text: "Home"
      - text: "Talks"
      - text: "About"
        file: about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/vmguerra/
      - icon: twitter
        href: https://twitter.com/vguerra
      - icon: github
        href: https://github.com/vguerra

  sidebar:
    style: floating
  page-footer:
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/vmguerra/
      - icon: twitter
        href: https://twitter.com/vguerra
      - icon: github
        href: https://github.com/vguerra

metadata-files: [nbdev.yml]